name: projectgeprekdiba
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  file_picker: ^5.0.0
  firebase_core: ^2.13.1
  flutter_rating_bar: ^4.0.0
  path_provider: ^2.0.11
  image_picker: ^0.8.7+5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/admin_profile.jpg
    - assets/admin_profile.png
    - assets/menu1.jpg
    - assets/menu2.jpg
    - assets/menu3.jpg
    - assets/menu4.jpg
    - assets/menu5.jpg
    - assets/sila.jpg
    - assets/indah.jpg
    - assets/wiwin.jpg
    - assets/default.jpg